fri-team/Swapify

APIWrapper/ResponseParser.cs, Backend/Converter/ConverterApiToDomain.cs, Backend/CourseService.cs, Backend/Interfaces/ICourseService.cs, Backend/StudyGroupService.cs, Entities/Block.cs, Entities/Timetable.cs, Tests/BackendTest/ConverterTest.cs, Tests/BackendTest/ParserTest.cs
- timetable for subject is now building continously (adding new discovered block)
-fixed bug in converter during converting
=> continual building timetable #51

Backend/Converter/ConverterApiToDomain.cs, Backend/CourseService.cs, Backend/DbRegistration.cs, Backend/Interfaces/IStudentService.cs, Backend/StudentService.cs, Backend/StudyGroupService.cs, Entities/Block.cs, Entities/Timetable.cs, Tests/BackendTest/ConverterTest.cs, Tests/BackendTest/DatabazeInitialization.cs, Tests/BackendTest/Mongo2GoFixture.cs, Tests/BackendTest/StudentServiceTest.cs, Tests/BackendTest/TimetableEditTest.cs, WebAPI/Startup.cs
- blocks on timetable are no more accessible directly but only thought add, delete or get method
=> Add, remove and edit block #58

Backend/DbSeed/DbSeed.cs, Backend/Settings/EnvironmentSettings.cs, Backend/Settings/IdentitySettings.cs, Backend/Settings/MailingSettings.cs, Backend/Settings/SettingsBase.cs, WebAPI/Filters/ValidationFilter.cs, WebAPI/Program.cs, WebAPI/Startup.cs
- Settings exceptions edit - created SettingsBase class
=> #96 Create DB Seed, log application startup

Backend/BlockChangesService.cs, Backend/Interfaces/IBlockChangesService.cs, Entities/BlockChangeRequest.cs, Entities/Enums/ExchangeStatus.cs, Entities/Student.cs, Tests/BackendTest/BlockChangeRequestTest.cs
Backend structure of request #106
=> structure, adding, removing and view exchanges #106

WebApp/src/components/Sidebar/Sidebar.js, WebApp/src/components/Sidebar/SidebarContainer.js
mockup for student's subject exchange request
=> #115 left side panel exteded with subject exchanges (mockup)

APIWrapper/Objects/ScheduleWeekContent.cs, APIWrapper/ResponseParser.cs, Tests/BackendTest/ParserTest.cs, Tests/BackendTest/ResponceParserTest.cs
=> Parser timetable fix after API change #123

Backend/DbSeed/DbSeed.cs, WebAPI/Controllers/TimetableController.cs, WebAPI/Models/UserModels/AuthenticatedUserModel.cs, WebAPI/Startup.cs, WebApp/src/actions/timetableActions.js, WebApp/src/reducers/userReducer.js
=> frontend add studentId

WebApp/package-lock.json, WebApp/package.json, WebApp/src/components/AddBlockForm/AddBlockForm.js, WebApp/src/components/AddBlockForm/Autocomplete.js, WebApp/src/components/Timetable/Timetable.js
Allow user to change time when he is adding new block and autofill for subject selection
=> Finish add new block

Backend/BlockChangesService.cs, Backend/DbSeed/DbSeed.cs, Backend/Interfaces/IBlockChangesService.cs, Tests/BackendTest/BlockChangeRequestTest.cs, WebAPI/Controllers/ExchangeController.cs, WebAPI/Startup.cs
Backend for "exchange panel" is ready to use.
=> 146 create backend for exchange panel

Backend/BlockChangesService.cs, Backend/Interfaces/IBlockChangesService.cs, Tests/BackendTest/BlockChangeRequestTest.cs, WebAPI/Controllers/ExchangeController.cs
Backend for the cancel exchange request is ready to use. Also test was added.
=> #151 cancel exchange with test

Backend/BlockChangesService.cs, WebApp/src/actions/timetableActions.js, WebApp/src/util/convertFunctions.js
There was bad time of blocks in exchange request showed in Sidebar and after successful exchange request  all exchange requests (including requests with status done) were deleted.
@marektavac please review
=> fix bad time and deleting

WebApp/src/components/HomePage/HomePage.js
=> removed hash from url in welcome page

WebApp/src/components/LoginPage/LoginPage.js, WebApp/src/components/Timetable/Timetable.scss, WebApp/src/components/TimetablePage/TimetablePage.js, WebApp/src/components/TimetablePage/TimetablePage.scss, WebApp/src/util/auth.js
* Fixed view of timetable - no need to use scrollbar to see whole timetable.
* Fixed homepage after logout - logout now works as expected. After logout is user redirected to homepage with active Login page from navigation.
* Fixed some Slovak strings on homepage to be grammaticaly correct.
=> #207 - Page size fix and some other fixes

WebApp/src/components/BlockDetail/BlockDetail.js, WebApp/src/components/HomePage/HomePage.scss, WebApp/src/containers/TimetableBlockContainer/TimetableBlockContainer.js
* block details are now displaying always inside of timeteble, without any overflowing.
=> #217 Fixed subject view

WebApp/src/components/Sidebar/SidebarContainer.js
fixed switcher on sidebar to show subject timetable
=> fixed subject timetable show

Backend/DbSeed/DbSeed.cs, Tests/IntegrationTest/ExchangeControllerTest/ExchangeControllerTests.cs, Tests/IntegrationTest/ExchangeControllerTest/ExchangeControllerTestsData.cs, Tests/IntegrationTest/IntegrationTest.csproj, Tests/IntegrationTest/TestFixture.cs, Tests/IntegrationTest/UserControllerTest/UserControllerTests.cs, WebAPI/Models/UserModels/AuthenticatedUserModel.cs, WebAPI/Startup.cs, WebApp/src/reducers/userReducer.js
I have created 3 integration tests for Exchange controller:
1. Exchange_ExchangeConfirm_Successful - test of a successful exchange
2. Exchange_ExchangeConfirm_NonAuthorizedCall - unauthorized user cannot ask for exchange
3. Exchange_ExchangeConfirm_UserNotFound - student which doesnt have an e-mail address (app does an exchange, but without mailing notification)
=> 224 create integration tests for exchange

WebApp/src/components/AddBlockForm/AddBlockForm.js, WebApp/src/components/BlockDetail/BlockDetail.js, WebApp/src/components/LoginPage/LoginPage.js, WebApp/src/components/LoginPage/LoginPage.scss, WebApp/src/components/Sidebar/Sidebar.js
* Added error texts (Server error responses) to Login page
* Added tooltips for buttons and functions in timetable
* Edited some labels to be gramatically correct
=> #229 Error texts at Login page && #243 Create tooltips

WebApp/src/components/BlockDetail/BlockDetail.js, WebApp/src/reducers/timetableReducer.js
* fixed ability to edit or apply for exchange to not be available for courses, that aren't user's
* fixed shading of courses during showing course's timetables to work correct
=> #256_Deploy_hotfix_timetable

Backend/Converter/ConverterApiToDomain.cs, Backend/CourseService.cs, Backend/DbSeed/DbSeed.cs, Backend/Interfaces/ICourseService.cs, WebAPI/Controllers/StudentController.cs, WebAPI/Controllers/TimetableController.cs, WebApp/src/components/AddBlockForm/AddBlockForm.js
=> Deploy hotfix - Add block #255

Backend/DbSeed/DbSeed.cs, Tests/BackendTest/StudentServiceTest.cs, Tests/BackendTest/TimetableEditTest.cs, WebAPI/Models/ExchangesModels/BlockForExchangeModel.cs, WebApp/src/actions/timetableActions.js
=> block id in BE tests  and exchange requests

Backend/EmailService.cs, Backend/Interfaces/IEmailService.cs, Backend/Settings/MailingSettings.cs, WebAPI/Controllers/UserController.cs, WebAPI/Models/UserModels/FeedbackModel.cs, WebAPI/appsettings.json
-now using EmailBase class
-user and password defined in appsettings.json
-renamed from "MailUs" to "SendFeedback" for more accurate description
-extended appsetting MailingSettings with new attribute FeedbackEmail where feedback will be sent
-attached example where i sent email to myself
=> 263 Mail Us (Feedback)

WebApp/src/components/Notifications/NotificationPanel.js, WebApp/src/components/Sidebar/Sidebar.js, WebApp/src/components/TimetablePage/TimetablePage.js, WebApp/src/components/Toolbar/Toolbar.js, WebApp/src/components/Toolbar/Toolbar.scss
* fixed width of side panel
* removed unnecesary field "Mailova adresa" from MailUs form
* changed way how icon "Notifications" is getting to app to be more consistent among with other icons
=> #270_Width_of_side_panel

WebApp/src/components/BlockDetail/BlockDetail.js
See issue #272 , if it works properly...
=> block teacher email and room text correction

APIWrapper/SchoolScheduleProxy.cs
* handled problem, that caused inactuality of timetable and also disfunction of changing timetable by personal number
=> #300 and #316 Timeteble inactual state and personal number change

WebApp/src/styles/styles.scss
=> Fix for side strip after clicking Contact us icon.

WebApp/src/components/Notifications/NotificationPanel.scss
Fixed notification default text position.
=> Positions of texts in notification window fixed.

.github/workflows/dotnetcore.yml, .travis.yml, Tests/BackendTest/BlockChangeRequestTest.cs, Tests/BackendTest/ResponceParserTest.cs, Tests/BackendTest/StudentServiceTest.cs
- completed workflow for CI build and tests
- few BE tests were commented and will be fixed in different story
- FE tests are temporary commented, because of automated gui test. FE and BE has to run, but BE wont run because of incorrect default mail settings in appsettings.json file.
=> #317 github action build and tests

Backend/CourseService.cs
Fix for #291 User story about adding new block in timetable.
=> Fix for adding new block.

WebApp/src/components/RegisterPage/RegisterPage.js
Confirmation message after submission of registration form.
=> Displays confirmation message.

.github/workflows/github_actions.yml, README.md
Changed badge of build in readme file.
=> Readme build badge

WebAPI/Startup.cs
localhost mongoDB connection works now :)
=> #378 local mongo connection n cors

WebApp/src/components/AddBlockForm/AddBlockForm.js, WebApp/src/components/BlockDetail/BlockDetail.js
Lectures can be removed and edited as intended. Also changed min max length of block
=> Lectures can be removed and edited as intended. Also changed min max … (#372)

Backend/DbSeed/DbSeed.cs, WebAPI/Startup.cs
#375 courses are loaded from json file (this has to be properly set in appsettings, currently path is "./courses_2020_1_29.json")
i also added oleg users to be created for testing on aws server (could be removed later, but i think its good idea to have them)
=> 375 mongo db for production

WebAPI/Controllers/UserController.cs, WebAPI/Startup.cs
Latest develop with uncommented useSpa() in Startup.cs. Everything works including email confirmation. Confirmatino links from before are invalid, since application on AWS server was rebuilt.
_Please merge this after review._
[http://18.193.17.141/](http://18.193.17.141/)
=> #393 400 requests not found

Backend/EmailService.cs, Backend/Interfaces/IEmailService.cs, WebAPI/Controllers/UserController.cs, WebAPI/Models/UserModels/FeedbackModel.cs, WebApp/src/actions/toolbarActions.js, WebApp/src/components/TimetablePage/TimetablePage.js
Mail us functionality on new version of develop. Functionality should work without harmful behaivior. #247
=> Mail us functionality on new version of develop.

WebApp/package-lock.json, WebApp/src/components/HomePage/HomePage.scss
Now registration page dynamically fit to users screen. #345
=> fixing problems with fitting registration page to smaller screens

Backend/Interfaces/ICourseService.cs, WebAPI/Controllers/StudentController.cs
This solves the #402 Unwanted change of subject upon edit.
=> Fix for editing subjects

WebApp/src/components/AddBlockForm/AddBlockForm.js
Changed addblock file where I changed handle change for block
=> 396 min max block length

Backend/DbSeed/DbSeed.cs, Entities/Student.cs, WebAPI/Models/UserModels/AuthenticatedUserModel.cs, WebApp/src/actions/timetableActions.js, WebApp/src/components/TimetablePage/TimetablePage.js, WebApp/src/containers/TimetableContainer/TimetableContainer.js, WebApp/src/reducers/userReducer.js
Added "personalNumber" to object "user" for easier identification of user's personal number. This helps to redirect new user after registration to "change personal number" prompt. #408
=> #408 first login prompt

WebApp/testsGUI/scenarios/deleteBlock.spec.js, WebApp/testsGUI/scenarios/editBlock.spec.js
GUI tests for delete and edit blocks on board. #399
=> #399_gui_tests2_delete_edit

WebApp/src/components/ConfirmEmailPage/ConfirmEmailPage.js
=> #407_email_home_button_fix

APIWrapper/Objects/CourseContent.cs, APIWrapper/Objects/ScheduleHourContent.cs, APIWrapper/ResponseParser.cs, APIWrapper/SchoolScheduleProxy.cs, Backend/Converter/ConverterApiToDomain.cs, Backend/CourseService.cs, Backend/Interfaces/ICourseService.cs, Entities/Course.cs, WebAPI/Controllers/StudentController.cs, WebAPI/Controllers/TimetableController.cs, WebAPI/Models/TimetableModels/TimetableBlock.cs, WebApp/src/components/AddBlockForm/AddBlockForm.js, WebApp/src/components/BlockDetail/BlockDetail.js, WebApp/src/components/Timetable/Timetable.js, WebApp/src/components/Timetable/TimetableBlock.js, WebApp/src/components/Timetable/TimetableBlocks.js, WebApp/src/components/Timetable/TimetableBlocks.test.js, WebApp/testsGUI/scenarios/addBlock.spec.js
This pull request does not solve issue 324. This issue is suspended for now. This request only fix naming of attributes.
=> fixing_naming_of_course_attributes

Entities/Block.cs, Entities/Timetable.cs, WebAPI/Controllers/StudentController.cs
Dame ID subject are not allowed to overlap now. #ItJustWorks
Closes #418
=> Same ID subjects are not allowed to overlap

WebApp/src/components/HomePage/HomePage.js, WebApp/src/components/HomePage/HomePage.scss
Added new styles for responsivity for home ,login and register page and also about us Closes #419
=> Added new styles

WebApp/src/actions/timetableActions.js, WebApp/src/components/AddBlockForm/Autocomplete.js, WebApp/src/components/BlockDetail/BlockDetail.js, WebApp/src/components/Sidebar/SideBarForm.js, WebApp/src/components/Sidebar/Sidebar.js, WebApp/src/components/Sidebar/SidebarContainer.js, WebApp/src/containers/BlockDetailContainer/BlockDetailContainer.js
user can add subject to timetable using plus icon in side bar #315 
https://user-images.githubusercontent.com/69460412/102720733-588dad00-42f6-11eb-8382-2cfa188acb13.mp4
=> 315 add new subject

Tests/BackendTest/BlockChangeRequestTest.cs, Tests/BackendTest/StudentServiceTest.cs
I checked tests that were commented out and realized that modified Class CourseService had no impact on them. Tests were ran and they passed.
=> #339 tests

WebApp/src/containers/TimetableBlockContainer/TimetableBlockContainer.js
=> problem with displaying block detail fixed

WebApp/src/components/BlockDetail/BlockDetail.js
=> #446 add subject doesnt send courseCode

WebAPI/appsettings.Production.json, docker-compose.yml, nginx.conf
Only changes required for migration.
=> changes_for_migration

Backend/CourseService.cs, Backend/Interfaces/ICourseService.cs, Tests/BackendTest/FindCoursesTest.cs, WebAPI/Controllers/TimetableController.cs, WebApp/src/components/AddBlockForm/AddBlockForm.js, WebApp/src/components/Sidebar/SideBarForm.js
=> #445 improvements in add block form

WebApp/testsGUI/scenarios/addBlock.spec.js
=> #450_GUI_Tests_3

WebApp/src/components/Toolbar/Toolbar.js, WebApp/src/containers/BlockDetailContainer/BlockDetailContainer.js, WebApp/src/reducers/__test__/hideCourseTimetable.json, WebApp/src/reducers/timetableReducer.js
=> #452 missing button  add subject

Dockerfile, docker-compose.yml, init-letsencrypt.sh, nginx.conf
Solution is fully inside docker container and does not need anything more than allowed traffic on ports 80 and 443. It uses nginx as reverse proxy to swapify application, which is exposed only inside container and certbot is used for automatically renewing certificate for https.
=> 436_https_solutions_with_nginx

.github/workflows/github_autodeploy_action.yml, WebAPI/Properties/launchSettings.json, WebAPI/Startup.cs, WebAPI/appsettings.Production.json, docker-compose.old.yml, docker-compose.yml
You can check how it works now on AWS before approving.
=> 463_dns_links

Entities/Block.cs, Entities/Timetable.cs, WebAPI/Controllers/StudentController.cs, WebAPI/Models/TimetableModels/TimetableBlock.cs, WebApp/package-lock.json, WebApp/package.json, WebApp/src/components/AddBlockForm/AddBlockForm.js, WebApp/src/components/BlockDetail/BlockDetail.js, WebApp/src/components/Timetable/TimetableBlock.js
=> #314 color of the timetable block

Backend/EmailService.cs, Backend/Interfaces/IUserService.cs, Backend/UserService.cs, Tests/BackendTest/UserControllerTests/UserControllerTests.cs, WebAPI/Controllers/StudentController.cs, WebAPI/Controllers/UserController.cs
New pull request because some changes that I did in this version are I think more indepth then previous. Also I wanna ask reviewers what is their opinion on using studentService in userController. But I wanna say there was no other way on backend side of things. fixes #499
=> #499 ldap bug

.github/workflows/github_actions.yml, APIWrapper/APIWrapper.csproj, Backend/AuthenticatorLdap.cs, Backend/Backend.csproj, Backend/Converter/ConverterApiToDomain.cs, Backend/CourseService.cs, Backend/EmailService.cs, Backend/Emails/EmailBase.cs, CoursesParser/CoursesParser.csproj, Dockerfile, Entities/Block.cs, Entities/Entities.csproj, README.md, Tests/BackendTest/BackendTest.csproj, Tests/IntegrationTest/IntegrationTest.csproj, WebAPI/Properties/launchSettings.json, WebAPI/WebAPI.csproj
Afterall it was quite easy to migrate to .NET 5. Just few changes but I left 3-4 warning where obselete things are used. Those can be refactored in next migration or separate task.
=> #506 upgrade to net 5

WebApp/testsGUI/scenarios/addBlock.spec.js, WebApp/testsGUI/scenarios/deleteBlock.spec.js, WebApp/testsGUI/scenarios/editBlock.spec.js, WebApp/testsGUI/steps_file.js
add, edit and delete block tests should be fixed
=> #512 gui tests not working well

WebApp/src/components/Timetable/TimetableBlock.js
=> fixed color changing of the subject

WebApp/src/components/AddBlockForm/AddBlockForm.js, WebApp/src/components/BlockDetail/BlockDetail.js
=> hot fix - now block detail window is changing color too

README.md, WebAPI/Program.cs, WebAPI/Startup.cs, WebAPI/WebAPI.csproj
Added Swagger documentation on link <webage_url>/swagger json file is… 
closes #530
=> Added Swagger documentation

WebApp/src/components/AddBlockForm/AddBlockForm.js
Included 12H format for block definition closes #528
=> Changed event handler for time management

WebApp/src/util/dateTimeFormatter.js
Days weren't displayed correctly, because server is responding with day as string, so I added function to convert day into the int for selecting correct day from array.
=> #526_Undefined_exchange_day

Backend/CalendarService.cs, Backend/Interfaces/ICalendarService.cs, SwapifyBase/Settings/CalendarSettings.cs, WebAPI/Controllers/StudentController.cs, WebAPI/Startup.cs, WebAPI/appsettings.json, WebApp/src/actions/timetableActions.js, WebApp/src/components/TimetablePage/TimetablePage.js, WebApp/src/components/Toolbar/Toolbar.js
just refactoring old solution. now you can export schedule to calendar.
=> #307 export to calendar refactored

WebApp/src/actions/timetableActions.js, WebApp/src/components/HomePage/HomePage.scss, WebApp/src/components/LoginPage/LoginPage.js
=> fri login page appear first

Backend/Converter/ConverterApiToDomain.cs
=> Merge subject block correctly without teacher name

Backend/AuthenticatorLdap.cs, WebAPI/Controllers/UserController.cs
Added better responses for events while login with ldap.
closes #550
=> Added better responses for LDAP login errors

APIWrapper/APIWrapper.csproj, APIWrapper/SchoolCourseProxy.cs, APIWrapper/SchoolScheduleProxy.cs, Backend/Backend.csproj, SwapifyBase/SwapifyBase.csproj, WebAPI/WebAPI.csproj, WebApp/package.json, WebApp/src/components/Timetable/TimetableBlock.scss, WebApp/src/components/Timetable/TimetableBlocks.js
=> broken timetable fix

WebApp/src/components/LoginPage/LoginPage.js
=> change_to_email_form

Backend/DbRegistration.cs, Tests/IntegrationTest/ExchangeControllerTest/ExchangeControllerTests.cs, Tests/IntegrationTest/ExchangeControllerTest/ExchangeControllerTestsData.cs, Tests/IntegrationTest/IntegrationTest.csproj, Tests/IntegrationTest/TestFixture.cs, Tests/IntegrationTest/UserControllerTest/UserControllerTests.cs, WebAPI/appsettings.integrationtest.json
The problem why the both category of integration cannot run at same time was that the one thread of tester try to insert into DB subjects that was already inserted by the other thread.
#485
=> #485 integration tests fix

WebAPI/appsettings.Production.json
Fixed naming of courses file. I somehow put wrong name of file into development settings.
=> Fixed namin of courses file

.github/workflows/github_autodeploy_action_stage.yml
=> last misstake fix

Backend/BlockChangesService.cs
Bug with multiple change requests in left panel fixed:
- While adding request to the database, we are checking wheter there is already same request, if yes, second request will not be added to the database -> no duplicities in the database and no multiple requests showing in the left panel of application.
=> 633 same changes multiple times

WebApp/src/components/TimetablePage/TimetablePage.js
The bug was coused by same background as coursor is. On this background si coursor visible.
=> #634 BUG fixed

WebApp/src/components/Toolbar/Toolbar.js
reset button for student timetable to remove all changes made to it
=> #595 reset button

WebApp/src/actions/timetableActions.js
Problem was that after requesting a change for subject, timetable stays in "grey" mode. I added a refresh after window "Žiadosť o zmenu bola evidovaná" is confirmed.
=> #632_issue_bug_solved

WebApp/src/components/Timetable/TimetableBlock.js, WebApp/src/components/Toolbar/Menu.js, WebApp/src/components/Toolbar/Toolbar.js
Just deleted useless console logs to not flod console while debugging another problem.
=> Deleted useless console logs
